/**
 * This file contains a list of all questions available on the give instance of SEAL.
 * TODO: In future this file should be generated by a script.
 */
import type { QuestionCollection } from "@shared/api/QuestionRouter"
import { DemoGraphEdgeInput } from "@shared/question-generators/demos/graphEdgeInput.ts"
import { DemoGraphNodeInput } from "@shared/question-generators/demos/graphNodeInput.ts"
import { DemoMultiInput } from "@shared/question-generators/demos/multiInput"
import { DemoMultipleChoice } from "@shared/question-generators/demos/multipleChoice"
import { DemoSingleInput } from "@shared/question-generators/demos/singleInput"

export const collection: QuestionCollection = [
  {
    slug: "demos",
    name: { de: "Demos", en: "Demos" },
    contents: [
      DemoGraphNodeInput,
      DemoGraphEdgeInput,
      DemoMultipleChoice,
      DemoSingleInput,
      DemoMultiInput,
    ],
  },
]
