/**
 * This file contains a list of all questions available on the give instance of SEAL.
 * TODO: In future this file should be generated by a script.
 */
import type { QuestionCollection } from "@shared/api/QuestionRouter"
import { DemoGraphEdgeInput } from "@shared/question-generators/demos/graphEdgeInput.ts"
import { DemoGraphs } from "@shared/question-generators/demos/graphGenerators"
import { DemoGraphNodeInput } from "@shared/question-generators/demos/graphNodeInput.ts"
import { DemoDraggingGraphs } from "@shared/question-generators/demos/interactiveGraphGenerator.ts"
import { DemoMultiInput } from "@shared/question-generators/demos/multiInput"
import { DemoMultipleChoice } from "@shared/question-generators/demos/multipleChoice"
import { DemoSingleInput } from "@shared/question-generators/demos/singleInput"
import { DemoSortingChoice } from "@shared/question-generators/demos/sorting.ts"
import { DemoTables } from "@shared/question-generators/demos/tables.ts"

export const collection: QuestionCollection = [
  {
    slug: "demos",
    name: { de: "Demos", en: "Demos" },
    topics: ["demo"],
    description: {
      en: "Collection of question to showcase website features",
      de: "Sammlung von Fragen zur Demonstration der Website-Funktionen",
    },
    contents: [
      DemoMultipleChoice,
      DemoSingleInput,
      DemoMultiInput,
      DemoGraphs,
      DemoDraggingGraphs,
      DemoGraphNodeInput,
      DemoGraphEdgeInput,
      DemoSortingChoice,
      DemoTables,
    ],
  },
]
