/**
 * This file contains a list of all questions available on the give instance of SEAL.
 * TODO: In future this file should be generated by a script.
 */
import type { QuestionCollection } from "@shared/api/QuestionRouter"
<<<<<<< HEAD:settings/questionsSelection.demos.ts
import { DemoMatching } from "@shared/question-generators/demos/matching.ts"
=======
import { DemoGraphs } from "@shared/question-generators/demos/graphGenerators"
import { DemoDraggingGraphs } from "@shared/question-generators/demos/interactiveGraphGenerator.ts"
>>>>>>> upstream/main:packages/settings/questionsSelection.demos.ts
import { DemoMultiInput } from "@shared/question-generators/demos/multiInput"
import { DemoMultipleChoice } from "@shared/question-generators/demos/multipleChoice"
import { DemoSingleInput } from "@shared/question-generators/demos/singleInput"
import { DemoSortingChoice } from "@shared/question-generators/demos/sorting.ts"
import { DemoTables } from "@shared/question-generators/demos/tables.ts"

export const collection: QuestionCollection = [
  {
    slug: "demos",
    name: { de: "Demos", en: "Demos" },
    contents: [
      DemoMultipleChoice,
      DemoSingleInput,
      DemoMultiInput,
<<<<<<< HEAD:settings/questionsSelection.demos.ts
      DemoSortingChoice,
      DemoTables,
      DemoMatching,
=======
      DemoGraphs,
      DemoDraggingGraphs,
      DemoSortingChoice,
      DemoTables,
>>>>>>> upstream/main:packages/settings/questionsSelection.demos.ts
    ],
  },
]
