import type {
  FreeTextQuestion,
  MultiFreeTextQuestion,
  MultipleChoiceQuestion,
  Question,
} from "../api/QuestionGenerator.ts"
import { parseMarkdown, type ParseTree, type ParseTreeNode } from "./parseMarkdown.ts"

export function toFraction(value: number): string {
  if (!Number.isFinite(value)) return String(value)
  if (Number.isInteger(value)) return String(value)
  const sign = value < 0 ? -1 : 1
  const x = Math.abs(value)
  const eps = 1e-12
  const maxDen = 1000000

  let a = Math.floor(x)
  let h1 = 1, k1 = 0
  let h = a, k = 1
  let x1 = x

  while (Math.abs(x - h / k) > eps && k <= maxDen) {
    x1 = 1 / (x1 - a)
    a = Math.floor(x1)
    const h2 = a * h + h1
    const k2 = a * k + k1
    h1 = h; k1 = k
    h = h2; k = k2
  }

  // if denominator grew too large, fallback to previous convergent
  if (k > maxDen) {
    h = h1
    k = k1
  }

  // reduce fraction
  const gcd = (a: number, b: number): number => {
    a = Math.abs(a); b = Math.abs(b)
    while (b) { const t = a % b; a = b; b = t }
    return a
  }
  let num = sign * h
  let den = k
  const g = gcd(num, den)
  num /= g; den /= g

  return den === 1 ? String(num) : `\\frac{${num}}{${den}}`
}

/**
 * Function to render a given markdown-like string in LaTeX
 *
 * @param md The markdown-like string to render
 * @returns The LaTeX string
 */
export function markdownToLatex(md: string): string {
  return markdownTreeToLatex(parseMarkdown(md))
}

/**
 * Function to replace quotes in a string by latex-style quotes
 * @example
 *   replaceQuotes(`"Hello world!"`) // => "``Hello world!''"
 */
function replaceQuotes(text: string) {
  return text.replace(/"([^"]*?)"/g, "``$1''")
}

/**
 * Function to render a given markdown-like string in LaTeX
 *
 * @param tree tree of parsed Markdown
 * @returns The LaTeX string
 */
export function markdownTreeToLatex(tree: ParseTree | ParseTreeNode): string {
  if (typeof tree === "string") {
    return replaceQuotes(tree).replaceAll("#", "\\#")
  } else if (Array.isArray(tree)) {
    return tree.map(markdownTreeToLatex).join("")
  } else if (tree.kind === "$") {
    return `$${tree.child}$`
  } else if (tree.kind === "$$") {
    return `\\[${tree.child}\\]`
  } else if (tree.kind === "*") {
    return `\\emph{${markdownTreeToLatex(tree.child)}}`
  } else if (tree.kind === "**") {
    return `\\textbf{${markdownTreeToLatex(tree.child)}}`
  } else if (tree.kind === "`") {
    return `\\texttt{${markdownTreeToLatex(tree.child)}}`
  } else if (tree.kind === "```") {
    return `\\begin{lstlisting}\n${markdownTreeToLatex(tree.child)}\n\\end{lstlisting}`
  } else if (tree.kind === ">") {
    return `\\begin{quote}\n${markdownTreeToLatex(tree.child)}\n\\end{quote}`
  } else if (tree.kind === "a") {
    return `\\href{${tree.url}}{${markdownTreeToLatex(tree.child)}}`
  } else if (tree.kind === "table") {
    const { content, format } = tree.child
    const colSpec = format.alignment
      .map((align, index) => {
        const vLine = format.hLines.includes(index) ? "|" : ""
        const spec = { left: "l", center: "c", right: "r" }[align]
        return `${spec}${vLine}`
      })
      .join("")

    const headerRow = format.header ? content[0] : undefined
    const bodyRows = format.header ? content.slice(1) : content
    const headerRowString = headerRow?.map(markdownTreeToLatex)?.join(" & ")
    const bodyRowsString = bodyRows
      .map((row, index) => {
        const hLine = format.hLines.includes(index + (headerRow ? 1 : 0)) ? "\\hline\n" : ""
        const rowString = row.map(markdownTreeToLatex).join(" & ")
        return `${rowString} \\\\\n${hLine}`
      })
      .join("")

    return `\n\n
    \\vspace{\\baselineskip}\\hspace{1cm}
\\begin{tabular}{${colSpec}}
${headerRowString ? headerRowString + " \\\\\n\\hline" : ""}
${bodyRowsString}
\\end{tabular}
\\vspace{\\baselineskip}\n\n`
  } else if (tree.kind === "input") {
    return `[[ ${tree.child.replaceAll("#", "\\#")} ]]`
  } else if (tree.kind === "list") {
    return `\\begin{itemize}
${tree.child.map((item) => "  \\item\n" + indent(markdownTreeToLatex(item.text).trim(), 4)).join("\n")}
\\end{itemize}`
  }

  // will never be reached:
  // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
  throw new Error(`Unsupported markdown tree kind: ${tree.kind}`)
}

/**
 * Function to indent a given string
 * @param text The string to indent
 * @param spaces The number of spaces to indent by
 * @returns The indented string
 */
export function indent(text: string, spaces: number = 2): string {
  const padding = " ".repeat(spaces)
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? padding + line : line))
    .join("\n")
}

/** Function to render the question in LaTeX */
export function questionToTex(question: Question): string {
  const t = question.type
  const template = `% Automatically generated by algo-learn on ${new Date().toISOString().split("T")[0]}
\\begin{exercise}[${markdownToLatex(question.name)}]% ${question.path} | ${t}
%INNER%
\\end{exercise}`
  if (t === "MultipleChoiceQuestion") {
    const q: MultipleChoiceQuestion = question
    const inner = indent(`${markdownToLatex(q.text ?? "")}
\\begin{itemize}
${q.answers.map((answer) => "  \\item\n" + indent(markdownToLatex(answer).trim(), 4)).join("\n")}
\\end{itemize}`)
    return template.replace("%INNER%", inner)
  } else if (t === "FreeTextQuestion") {
    const q: FreeTextQuestion = question
    const inner = markdownToLatex(q.text ?? "").trim() + "\n\n" + markdownToLatex(q.prompt ?? "").trim()
    return template.replace("%INNER%", indent(inner, 2))
  } else if (t === "MultiFreeTextQuestion") {
    const q: MultiFreeTextQuestion = question
    const inner = markdownToLatex(q.text ?? "").trim()
    return template.replace("%INNER%", indent(inner, 2))
  } else {
    throw new Error(`Unsupported question type: ${t}`)
  }
}
